### ISSUE TITLE
Premium Edition

### ISSUE THREAD

**Issue by theangryangel** [BerryWorksSoftware/edi-json#13]
Hi,

I'm reaching out here, because I don't think I've had any response from the json@ address in the README (apologies if I have, but I've not found it in spam/quarantine).

The company I work for (@GlodoUK) is interested in getting read/write capabilities from X12 (and later down the line likely EDIFACT), and I think edi-json is probably one of the easier solutions to get into our existing workflows.

We're basically after pricing/support model at this point to be able to get an understanding of where it fits in the ecosystem.

**Comment by canabrook** [comment]
Hi Karl,

Thanks for diligence in making contact. The email setup changed, and apparently the json @ forwarding got dropped. 

The JSON-based integration is certainly more common these days, replacing the earlier XML-based approaches. Fortunately, the underlying EDI parser and framework is not tightly coupled with either, so both JSON and XML are equally supported, in either direction, and for EDIFACT as well as X12. 

Please contact me at ***@***.*** ***@***.***> for pricing other other information.

Scott
